version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    command: --server-id=1 --log-bin=mysql-bin
    volumes:
      - master-data:/var/lib/mysql

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    command: --server-id=2 --relay-log=mysql-relay-bin
    volumes:
      - slave-data:/var/lib/mysql
    depends_on:
      - master

volumes:
  master-data:
  slave-data:
